#!/bin/bash
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Script to generate version.g.dart files for all packages
# Finds all packages/*/pubspec.yaml files, extracts version, and writes to package/lib/version.g.dart

set -e

# Get the script directory (project root)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Find all pubspec.yaml files in packages directory
find "$SCRIPT_DIR/packages" -name "pubspec.yaml" -type f | while read -r pubspec_file; do
  # Get the package directory (parent of pubspec.yaml)
  package_dir="$(dirname "$pubspec_file")"
  package_name="$(basename "$package_dir")"
  
  # Extract version from pubspec.yaml (format: version: X.Y.Z)
  version=$(grep -E "^version:" "$pubspec_file" | sed -E 's/^version:[[:space:]]*//' | tr -d '[:space:]')
  
  if [ -z "$version" ]; then
    echo "Warning: Could not find version in $pubspec_file, skipping..."
    continue
  fi
  
  # Create lib directory if it doesn't exist
  lib_dir="$package_dir/lib"
  mkdir -p "$lib_dir"
  
  # Write version.g.dart file
  version_file="$lib_dir/version.g.dart"
  cat > "$version_file" << EOF
// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// GENERATED CODE - DO NOT MODIFY BY HAND
// This file is generated by gen-version.sh

/// The current version of the package.
const String packageVersion = '$version';
EOF
  
  echo "Generated $version_file with version: $version"
done

echo "Version generation complete!"
