#!/bin/bash

# Script to generate version.g.dart files for all packages
# Finds all packages/*/pubspec.yaml files, extracts version, and writes to package/lib/version.g.dart

set -e

# Get the script directory (project root)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Find all pubspec.yaml files in packages directory
find "$SCRIPT_DIR/packages" -name "pubspec.yaml" -type f | while read -r pubspec_file; do
  # Get the package directory (parent of pubspec.yaml)
  package_dir="$(dirname "$pubspec_file")"
  package_name="$(basename "$package_dir")"
  
  # Extract version from pubspec.yaml (format: version: X.Y.Z)
  version=$(grep -E "^version:" "$pubspec_file" | sed -E 's/^version:[[:space:]]*//' | tr -d '[:space:]')
  
  if [ -z "$version" ]; then
    echo "Warning: Could not find version in $pubspec_file, skipping..."
    continue
  fi
  
  # Create lib directory if it doesn't exist
  lib_dir="$package_dir/lib"
  mkdir -p "$lib_dir"
  
  # Write version.g.dart file
  version_file="$lib_dir/version.g.dart"
  cat > "$version_file" << EOF
// GENERATED CODE - DO NOT MODIFY BY HAND
// This file is generated by gen-version.sh

/// The current version of the package.
const String packageVersion = '$version';
EOF
  
  echo "Generated $version_file with version: $version"
done

echo "Version generation complete!"