name: firebase_admin_sdk_workspace
publish_to: none

environment:
  sdk: ^3.9.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  melos: ^7.3.0
  test: ^1.26.3

workspace:
  - packages/firebase_admin_sdk
  - packages/google_cloud_firestore
  - packages/firebase_admin_sdk/example
  - packages/firebase_admin_sdk/example_server_app

melos:
  scripts:
    docs:
      description: Generate documentation for all packages
      run: ../../scripts/generate-docs.sh
      exec:
        concurrency: 1
      select-package:
        - '*'
      packageFilters:
        flutter: false
        ignore:
          - "*example*"

  command:
    bootstrap:
      hooks:
        post: ./scripts/gen-version.sh
    version:
      hooks:
        post: ./scripts/gen-version.sh

dependency_overrides:
  google_cloud:
    git:
      url: https://github.com/googleapis/google-cloud-dart
      path: pkgs/google_cloud
