name: dart_firebase_admin_example_server_app
publish_to: none

resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  dart_firebase_admin:
  shelf: ^1.4.2
  shelf_router: ^1.1.2

dev_dependencies:
  http: ^1.2.2
  test: ^1.25.6
