name: dart_firebase_admin_example
publish_to: none

environment:
  sdk: '^3.9.0'

dependencies:
  dart_firebase_admin: ^0.1.0
  google_cloud_storage: ^0.1.0
  googleapis_firestore: ^0.1.0

dependency_overrides:
  dart_firebase_admin:
    path: ../../dart_firebase_admin
  google_cloud_storage:
    path: ../../google_cloud_storage
  googleapis_firestore:
    path: ../../googleapis_firestore

