name: firebase_admin_sdk
description: A Firebase Admin SDK implementation for Dart.
resolution: workspace
version: 0.5.0
repository: https://github.com/firebase/firebase-admin-dart/tree/main/packages/firebase_admin_sdk

environment:
  sdk: ^3.9.0

dependencies:
  asn1lib: ^1.6.0
  collection: ^1.19.1
  dart_jsonwebtoken: ^3.2.0
  equatable: ^2.0.7
  ffi: ^2.2.0
  google_cloud: ^0.4.0
  google_cloud_firestore: ^0.5.0
  google_cloud_storage: ^0.6.0
  googleapis: ^16.0.0
  googleapis_auth: ^2.3.0
  googleapis_beta: ^9.0.0
  http: ^1.6.0
  intl: ^0.20.0
  meta: ^1.18.1
  pem: ^2.0.6
  pointycastle: ^4.0.0

dev_dependencies:
  build_runner: ^2.4.7
  file: ^7.0.1
  mocktail: ^1.0.2
  path: ^1.9.1
  test: ^1.26.3
  uuid: ^4.0.0

false_secrets:
 - /test/unit/auth/jwt_test.dart
 - /test/fixtures/mock_service_account.dart
 - /test/unit/app/credential_test.dart
