#!/bin/bash

# Script to generate version.g.dart files for all packages
# Finds all packages/*/pubspec.yaml files, extracts version, and writes to package/lib/version.g.dart

set -e

# Get the script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Project root is the parent directory
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

package_dir="$PROJECT_ROOT/packages/dart_firebase_admin"
pubspec_file="$package_dir/pubspec.yaml"

# Extract version from pubspec.yaml (format: version: X.Y.Z)
version=$(grep -E "^version:" "$pubspec_file" | sed -E 's/^version:[[:space:]]*//' | tr -d '[:space:]')

if [ -z "$version" ]; then
  echo "Error: Could not find version in $pubspec_file"
  exit 1
fi

# Create lib/src directory if it doesn't exist
src_dir="$package_dir/lib/src"
mkdir -p "$src_dir"

# Write version.g.dart file
version_file="$src_dir/version.g.dart"
cat > "$version_file" << EOF
// GENERATED CODE - DO NOT MODIFY BY HAND
// This file is generated by gen-version.sh

/// The current version of the package.
const String packageVersion = '$version';
EOF

echo "Generated $version_file with version: $version"

echo "Version generation complete!"