#!/bin/bash

# Script to generate version.g.dart for firebase_admin_sdk
# Extracts version from pubspec.yaml and writes to lib/src/version.g.dart

set -euo pipefail

# Get the script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Project root is the parent directory
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

package_dir="$PROJECT_ROOT/packages/firebase_admin_sdk"
pubspec_file="$package_dir/pubspec.yaml"

# Extract version from pubspec.yaml (format: version: X.Y.Z)
version=$(grep -E "^version:" "$pubspec_file" | head -n 1 | sed -E 's/^version:[[:space:]]*([^[:space:]#]*).*/\1/' || true)

if [ -z "$version" ]; then
  echo "Error: Could not find version in $pubspec_file"
  exit 1
fi

# Create lib/src directory if it doesn't exist
src_dir="$package_dir/lib/src"
mkdir -p "$src_dir"

# Write version.g.dart file
version_file="$src_dir/version.g.dart"
cat > "$version_file" << EOF
// GENERATED CODE - DO NOT MODIFY BY HAND
// This file is generated by scripts/gen-version.sh

/// The current version of the package.
const String packageVersion = '$version';
EOF

echo "Generated $version_file with version: $version"
